### ISSUE TITLE
Force create output directory

### ISSUE THREAD

**Issue by JeffreyWay** [stephenmathieson/node-concatenate#2]
I noticed that if you specify an output path that doesn't yet exist, it'll fail.

```js
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 
```

Anyway to have this plugin force-create the directory, if it doesn't exist?

**Comment by stephenmathieson** [comment]
You could use the `mkdirp` module to ensure the parent directory exists. Doesn't seem like a worry that belongs in this modules scope.
